Move the --purgec option to the right place on two iget commands lines in testiCommands.pl so that 'devtest' can succeed on Mac OS X.
It seems to work OK in the other place on other OSes (at least Ubuntu)
but on Macs produces odd errors.  For example:
iget -f /tempZone/home/rods/icmdtest/foo7 --purgec /tbox/IRODS_BUILD/iRODS/clients/icommands/test/foo7
produces:
ERROR: resolveRodsTarget: srcPath /tempZone/home/rods/-Z does not exist
ERROR: getUtil: resolveRodsTarget status = -317000 USER_INPUT_PATH_ERR



git-svn-id: svn://irodssvn.ucsd.edu/trunk@4831 ea137bd6-aa86-47b6-b90d-b101d9f19a90